/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.fd;

import Connect.JavaConnectDB;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import org.apache.poi.ss.usermodel.FormulaEvaluator;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author hites
 */
public class Add_staff extends javax.swing.JFrame {

    Connection con = null, con1 = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    OracleResultSet rs1 = null;
    String branch = null, semester;
    String div, name = null, surname = null, subject, initial = null, sub = null, roll_id = null;
    int count;
    String coun, password;
    int c = 1;
    String cnt;
    Vector v = new Vector();

    /**
     * Creates new form Add_staff
     */
    public Add_staff() {
        initComponents();
        TableColumnModel columnModel = staff_info.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(20);
        columnModel.getColumn(3).setPreferredWidth(90);
        columnModel.getColumn(4).setPreferredWidth(90);
        columnModel.getColumn(5).setPreferredWidth(30);
        columnModel.getColumn(6).setPreferredWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        branch_box2 = new javax.swing.JComboBox();
        Back = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staff_info = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No. of  Staffs:-");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Branch:-");

        branch_box2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CO", "EJ", "IF" }));
        branch_box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_box2ActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        staff_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Branch", "Staff_ID", "Name", "Surname", "Initial", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staff_info.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(staff_info);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Rows");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Import");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(branch_box2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(branch_box2))
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(Back)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Number, branch_box2, jLabel1, jLabel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branch_box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_box2ActionPerformed
        branch = (String) branch_box2.getSelectedItem();        // TODO add your handling code here:
    }//GEN-LAST:event_branch_box2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new AdminPage().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        con = JavaConnectDB.ConnectDB();
        DefaultTableModel th_dtm = (DefaultTableModel) staff_info.getModel();
        while (th_dtm.getRowCount() > 0) {
            for (int i = 0; i < th_dtm.getRowCount(); i++) {
                th_dtm.removeRow(i);
            }
        }
        try {
            count = Integer.parseInt(Number.getText());
            for (int i = 0; i < count; i++) {
                DefaultTableModel model = (DefaultTableModel) staff_info.getModel();
                model.insertRow(staff_info.getRowCount(), new Object[]{i + 1, branch});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_OkActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        con1 = JavaConnectDB.ConnectDB();
        int row = staff_info.getRowCount();
        try {
            for (int i = 0; i < row; i++) {
                branch = (String) staff_info.getValueAt(i, 1);
                roll_id = (String) staff_info.getValueAt(i, 2);
                name = (String) staff_info.getValueAt(i, 3);
                surname = (String) staff_info.getValueAt(i, 4);
                initial = (String) staff_info.getValueAt(i, 5);
                password = (String) staff_info.getValueAt(i, 6);
                String sql = "insert into  staff_info values (?,?,?,?,?,?)";
                pst = (OraclePreparedStatement) con1.prepareStatement(sql);
                pst.setString(1, roll_id.toUpperCase());
                pst.setString(2, name.toUpperCase());
                pst.setString(3, surname.toUpperCase());
                pst.setString(4, initial.toUpperCase());
                pst.setString(6, branch.toUpperCase());
                pst.setString(5, password.toUpperCase());
                rs = (OracleResultSet) pst.executeQuery();
                String sql2 = "delete from staff_info where name=null and surname=null and initials=null";
                pst = (OraclePreparedStatement) con1.prepareStatement(sql2);
                rs1 = (OracleResultSet) pst.executeQuery();
            }
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Sucessfully added");
                DefaultTableModel th_dtm = (DefaultTableModel) staff_info.getModel();
                while (th_dtm.getRowCount() > 0) {
                    for (int j = 0; j < th_dtm.getRowCount(); j++) {
                        th_dtm.removeRow(j);
                    }
                }
            }
        } catch (NullPointerException n) {
            JOptionPane.showMessageDialog(null, "Please delete extra rows...");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // Add.setEnabled(false);
        Number.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel th_dtm = (DefaultTableModel) staff_info.getModel();
        int row = staff_info.getSelectedRow();
        th_dtm.removeRow(row);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel th_dtm = (DefaultTableModel) staff_info.getModel();
        while (th_dtm.getRowCount() > 0) {
            for (int i = 0; i < th_dtm.getRowCount(); i++) {
                th_dtm.removeRow(i);
            }
        }
        String Excelpath = null;
        try {
            FileInputStream fs = null;
            JFileChooser jf = new JFileChooser();
            jf.setDialogTitle("Save Excel File");
            int res = jf.showSaveDialog(null);
            if (res == JFileChooser.APPROVE_OPTION) {
                Excelpath = jf.getSelectedFile().getAbsolutePath();
            }
            try {
                fs = new FileInputStream(Excelpath);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            XSSFWorkbook wb = new XSSFWorkbook(fs);
            String[] strs = new String[wb.getNumberOfSheets()];
            //get all sheet names from selected workbook
            for (int i = 0; i < strs.length; i++) {
                strs[i] = wb.getSheetName(i);
            }
            JFrame frame = new JFrame("Input Dialog");
            int index = 0;
            String selectedsheet = (String) JOptionPane.showInputDialog(frame, "Which worksheet you want to import ?", "Select Worksheet", JOptionPane.QUESTION_MESSAGE, null, strs, strs[0]);
            if (selectedsheet != null) {
                for (int i = 0; i < strs.length; i++) {
                    if (wb.getSheetName(i).equalsIgnoreCase(selectedsheet)) {
                        index = i;
                    }
                }
            }
            XSSFSheet sh = wb.getSheetAt(index);
            FormulaEvaluator fe = (FormulaEvaluator) wb.getCreationHelper().createFormulaEvaluator();

            for (Row row : sh) {
                for (org.apache.poi.ss.usermodel.Cell cell : row) {
                    switch (fe.evaluateInCell(cell).getCellType()) {
                        case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_NUMERIC:
                            int num = (int) cell.getNumericCellValue();
                            //v.addElement(num);
                            v.add(num);
                            break;
                        case org.apache.poi.ss.usermodel.Cell.CELL_TYPE_STRING:
                            String n = cell.getStringCellValue();
                            //v.addElement(n);
                            v.add(n);
                            break;
                    }
                }

                if (!v.isEmpty()) {
                    coun = v.elementAt(0).toString();
                    cnt = Integer.toString(c);
                    if (coun.equals(cnt)) {
                        if (!v.isEmpty()) {
                            DefaultTableModel tabmod = (DefaultTableModel) staff_info.getModel();
                            tabmod.insertRow(staff_info.getRowCount(), new Object[]{v.elementAt(0).toString().toUpperCase(), v.elementAt(1).toString().toUpperCase(), v.elementAt(2).toString().toUpperCase(), v.elementAt(3).toString().toUpperCase(), v.elementAt(4).toString().toUpperCase(), v.elementAt(5).toString().toUpperCase(), v.elementAt(6).toString().toUpperCase()});
                            v.removeAllElements();
                            c = c + 1;
                        }
                    } else {
                        v.removeAllElements();
                    }
                }
            }
            c = 1;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Number;
    private javax.swing.JButton Ok;
    private javax.swing.JComboBox branch_box2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable staff_info;
    // End of variables declaration//GEN-END:variables
}
