/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.fd;

import Connect.JavaConnectDB;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import oracle.jdbc.*;

/**
 *
 * @author hites
 */
public class StudentLoginPage extends javax.swing.JFrame {

    Connection con = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    OracleResultSet rs1 = null;
    String div;
    String Branch;
    String sem;
    String name;
    String username, us;

    /**
     * Creates new form StudentLoginPage
     */
    public StudentLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Student_Username = new javax.swing.JTextField();
        Student_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Student_Password = new javax.swing.JPasswordField();
        Student_Login = new javax.swing.JButton();
        Student_Cancel = new javax.swing.JButton();
        Chnage_Password = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password:-");

        Student_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Student_UsernameKeyPressed(evt);
            }
        });

        Student_Back.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        Student_Back.setText("Back");
        Student_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username:-");

        Student_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Student_PasswordKeyPressed(evt);
            }
        });

        Student_Login.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        Student_Login.setText("Login");
        Student_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_LoginActionPerformed(evt);
            }
        });

        Student_Cancel.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        Student_Cancel.setText("Cancel");
        Student_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_CancelActionPerformed(evt);
            }
        });

        Chnage_Password.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        Chnage_Password.setText("Change Password");
        Chnage_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chnage_PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Student_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Student_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Student_Username)
                            .addComponent(Student_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Chnage_Password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Student_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Student_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chnage_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Student_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Student_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Chnage_Password, Student_Cancel, Student_Login});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Student_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_BackActionPerformed
        new FirstPage().setVisible(true);
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_Student_BackActionPerformed

    private void Student_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_LoginActionPerformed
        con = JavaConnectDB.ConnectDB();
        try {
            String sql9 = "select * from student_info where roll_id=? and password=?";
            pst = (OraclePreparedStatement) con.prepareStatement(sql9);
            pst.setString(1, Student_Username.getText().toUpperCase());
            pst.setString(2, Student_Password.getText().toUpperCase());
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                div = rs.getString("DIVISION");
                Branch = rs.getString("BRANCH");
                sem = rs.getString("semester");
            }
            if (Branch.equals("CO")) {
                String sql5 = "select co_username from login_data where co_username is not null and co_username=?";
                pst = (OraclePreparedStatement) con.prepareStatement(sql5);
                pst.setString(1, Student_Username.getText().toUpperCase());
                rs = (OracleResultSet) pst.executeQuery();
                if (rs.next()) {
                    name = rs.getString("co_username").toUpperCase();
                    username = Student_Username.getText().toUpperCase();
                    if (username.equals(name)) {
                        throw new myEx("You have already given the feedback");
                    }
                }
            } else if (Branch.equals("IF")) {
                String sql6 = "select if_username from login_data where if_username is not null and if_username=? ";
                pst = (OraclePreparedStatement) con.prepareStatement(sql6);
                pst.setString(1, Student_Username.getText().toUpperCase());
                rs = (OracleResultSet) pst.executeQuery();
                if (rs.next()) {
                    name = rs.getString("if_username").toUpperCase();
                    username = Student_Username.getText().toUpperCase();
                    if (username.equals(name)) {
                        throw new myEx("You have already given the feedback");
                    }
                }
            } else if (Branch.equals("EJ")) {
                String sql7 = "select ej_username from login_data where ej_username is not null and ej_username=? ";
                pst = (OraclePreparedStatement) con.prepareStatement(sql7);
                rs = (OracleResultSet) pst.executeQuery();
                if (rs.next()) {
                    name = rs.getString("ej_username").toUpperCase();
                    username = Student_Username.getText().toUpperCase();
                    if (username.equals(name)) {
                        throw new myEx("You have already given the feedback");
                    }
                }
            }
            String sql4 = "select * from student_info where roll_id=? and password=?";
            pst = (OraclePreparedStatement) con.prepareStatement(sql4);
            pst.setString(1, Student_Username.getText().toUpperCase());
            pst.setString(2, Student_Password.getText().toUpperCase());
            rs1 = (OracleResultSet) pst.executeQuery();
            if (rs1.next()) {
                div = rs1.getString("DIVISION");
                Branch = rs1.getString("BRANCH");
                sem = rs1.getString("Semester");
                us = Student_Username.getText().toUpperCase();
                new E_FeedBackForm(Branch, div, sem, us).setVisible(true);
                this.dispose();
            }
        } catch (myEx es) {
            JOptionPane.showMessageDialog(null, "You have already given the feedback");
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(null, "Username And Password Are InCorrect.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Student_LoginActionPerformed

    private void Student_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_CancelActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Student_CancelActionPerformed

    private void Student_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_PasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Student_Login.doClick();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_Student_PasswordKeyPressed

    private void Student_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Student_UsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Student_Login.doClick();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_Student_UsernameKeyPressed

    private void Chnage_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chnage_PasswordActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Do you want to really change your passsword?", "Change Password", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            new change_password().setVisible(true);
            this.dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_Chnage_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginPage().setVisible(true);
            }
        });
    }

    class myEx extends Exception {

        myEx(String msg) {
            super(msg);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chnage_Password;
    private javax.swing.JButton Student_Back;
    private javax.swing.JButton Student_Cancel;
    private javax.swing.JButton Student_Login;
    private javax.swing.JPasswordField Student_Password;
    private javax.swing.JTextField Student_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
