/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.fd;

import Connect.JavaConnectDB;
import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author hites
 */
public class sub extends javax.swing.JFrame {

    Connection con = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    OracleResultSet rs1 = null, rs4;
    String branch, name, surname, name1, surname1, None = null, initial, initial1, subject, sub;
    String semester, div, th_n = null, pr_n;
    String WHITESPACE = " ", n;

    /**
     * Creates new form sub
     */
    public sub() {
        initComponents();
        con = JavaConnectDB.ConnectDB();
        fillall();
    }

    private void fillall() {
        con = JavaConnectDB.ConnectDB();
        th_name.removeAllItems();
        pr_name2.removeAllItems();
        th_name.addItem(None);
        pr_name2.addItem(None);
        String sql = "select name,surname,initials from staff_info";
        try {
            pst = (OraclePreparedStatement) con.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            while (rs.next()) {
                name = rs.getString("name");
                surname = rs.getString("surname");
                n = name.concat(WHITESPACE).concat(surname);
                th_name.addItem(n);
                pr_name2.addItem(n);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b_box = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        s_box = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        d_box = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        sub_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        abbr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pr_name2 = new javax.swing.JComboBox();
        th_name = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Branch:-");

        b_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CO", "IF", "EJ" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Semester:-");

        s_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        s_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_boxActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Division:-");

        d_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Subject Name:-");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Abbreviation:- ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Name_of_prof.(th):-");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Name_of_prof.(pr):-");

        pr_name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_name2ActionPerformed(evt);
            }
        });

        th_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th_nameActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(th_name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(b_box, 0, 64, Short.MAX_VALUE)
                                        .addComponent(s_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(d_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(sub_name)
                                    .addComponent(abbr, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pr_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_box, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_box, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_box, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abbr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(th_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pr_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdminPage().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_boxActionPerformed

    private void pr_name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pr_name2ActionPerformed

    private void th_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_th_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        con = JavaConnectDB.ConnectDB();
        branch = (String) b_box.getSelectedItem();
        semester = (String) s_box.getSelectedItem();
        div = (String) d_box.getSelectedItem();
        subject = sub_name.getText();
        sub = abbr.getText().toUpperCase();
        n = (String) th_name.getSelectedItem();
        String[] parts = n.split(" ");
        name = parts[0];
        surname = parts[1];
        String n1 = (String) pr_name2.getSelectedItem();
        String[] part = n1.split(" ");
        name1 = part[0];
        surname1 = part[1];
        try {
            if (n.equals(null)) {

                String sql2 = "select initials from staff_info where name=? and surname=?";
                pst = (OraclePreparedStatement) con.prepareStatement(sql2);
                pst.setString(1, name);
                pst.setString(2, surname);
                rs = (OracleResultSet) pst.executeQuery();
                while (rs.next()) {
                    initial = rs.getString("initials");
                }
                String sql1 = "insert into subject_info (branch,semester,division,subject,PRACTICAL_NAME_OF_PROF,full_sub_name) values (?,?,?,?,?,?)";
                pst = (OraclePreparedStatement) con.prepareStatement(sql1);
                pst.setString(5, initial);
                pst.setString(4, sub);
                pst.setString(3, div);
                pst.setString(1, branch);
                pst.setString(2, semester);
                pst.setString(6, subject);
                rs1 = (OracleResultSet) pst.executeQuery();
                while (rs1.next()) {
                    JOptionPane.showMessageDialog(null, "Sucessfully added");
                }
            } else if (n1.equals(null)) {
                String sql2 = "select initials from staff_info where name=? and surname=?";
                pst = (OraclePreparedStatement) con.prepareStatement(sql2);
                pst.setString(1, name1);
                pst.setString(2, surname1);
                rs = (OracleResultSet) pst.executeQuery();
                while (rs.next()) {
                    initial = rs.getString("initials");
                }
                String sql1 = "insert into subject_info (branch,semester,division,subject,THEORY_NAME_OF_PROF,full_sub_name) values (?,?,?,?,?,?)";
                pst = (OraclePreparedStatement) con.prepareStatement(sql1);
                pst.setString(5, initial);
                pst.setString(4, sub);
                pst.setString(3, div);
                pst.setString(1, branch);
                pst.setString(2, semester);
                pst.setString(6, subject);
                rs1 = (OracleResultSet) pst.executeQuery();
                while (rs1.next()) {
                    JOptionPane.showMessageDialog(null, "Sucessfully added");
                }
            } else {
                String sql = "select initials from staff_info where name=? and surname=?";
                pst = (OraclePreparedStatement) con.prepareStatement(sql);
                pst.setString(1, name1);
                pst.setString(2, surname1);
                rs = (OracleResultSet) pst.executeQuery();
                while (rs.next()) {
                    initial1 = rs.getString("initials");
                }
                String sql2 = "select initials from staff_info where name=? and surname=?";
                pst = (OraclePreparedStatement) con.prepareStatement(sql2);
                pst.setString(1, name);
                pst.setString(2, surname);
                rs1 = (OracleResultSet) pst.executeQuery();
                while (rs1.next()) {
                    initial = rs1.getString("initials");
                }
                String sql1 = "insert into subject_info (branch,semester,division,subject,THEORY_NAME_OF_PROF,PRACTICAL_NAME_OF_PROF,full_sub_name) values (?,?,?,?,?,?,?)";
                pst = (OraclePreparedStatement) con.prepareStatement(sql1);
                pst.setString(5, initial);
                pst.setString(4, sub);
                pst.setString(3, div);
                pst.setString(1, branch);
                pst.setString(2, semester);
                pst.setString(6, initial1);
                pst.setString(7, subject);
                rs4 = (OracleResultSet) pst.executeQuery();
                while (rs4.next()) {
                    JOptionPane.showMessageDialog(null, "Sucessfully added");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abbr;
    private javax.swing.JComboBox b_box;
    private javax.swing.JComboBox d_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox pr_name2;
    private javax.swing.JComboBox s_box;
    private javax.swing.JTextField sub_name;
    private javax.swing.JComboBox th_name;
    // End of variables declaration//GEN-END:variables
}
